  - ExtWm
  - BER
  - TPR@xFPR:
      report_name: tpr@10%fpr
      fpr_rate: 0.1
  - TPR@xFPR:
      report_name: tpr@1%fpr
      fpr_rate: 0.01
  - TPR@xFPR:
      report_name: tpr@0.1%fpr
      fpr_rate: 0.001
  - TPR@xFPR:
      report_name: tpr@0.01%fpr
      fpr_rate: 0.0001
  - TPR@xFPR:
      report_name: tpr@0.001%fpr
      fpr_rate: 0.00001
  - TPR@xFPR:
      report_name: tpr@0.0001%fpr
      fpr_rate: 0.000001
  - TPR@xFPR:
      report_name: tpr@0.00001%fpr
      fpr_rate: 0.0000001
  - TPR@xFPR:
      report_name: tpr@0.000001%fpr
      fpr_rate: 0.00000001