from dfsrc_disco.robustbench.model_zoo.defense.randomization import Randomization
from dfsrc_disco.robustbench.model_zoo.defense.bit_depth_reduction import BitDepthReduction
from dfsrc_disco.robustbench.model_zoo.defense.jpeg_compression import Jpeg_compresssion
