 - instagram_attacks:
    report_name: _1977 
    attack: _1977
 - instagram_attacks:
    report_name: aden
    attack: aden
 - instagram_attacks:
    report_name: brannan
    attack: brannan
 - instagram_attacks:
    report_name: brooklyn
    attack: brooklyn
 - instagram_attacks:
    report_name: clarendon
    attack: clarendon
 - instagram_attacks:
    report_name: earlybird
    attack: earlybird
 - instagram_attacks:
    report_name: gingham
    attack: gingham
 - instagram_attacks:
    report_name: hudson
    attack: hudson
 - instagram_attacks:
    report_name: inkwell
    attack: inkwell
 - instagram_attacks:
    report_name: kelvin
    attack: kelvin
 - instagram_attacks:
    report_name: lark
    attack: lark
 - instagram_attacks:
    report_name: lofi
    attack: lofi
 - instagram_attacks:
    report_name: maven
    attack: maven
 - instagram_attacks:
    report_name: mayfair
    attack: mayfair
 - instagram_attacks:
    report_name: moon
    attack: moon
 - instagram_attacks:
    report_name: nashville
    attack: nashville
 - instagram_attacks:
    report_name: perpetua
    attack: perpetua
 - instagram_attacks:
    report_name: reyes
    attack: reyes
 - instagram_attacks:
    report_name: rise
    attack: rise
 - instagram_attacks:
    report_name: slumber
    attack: slumber
 - instagram_attacks:
    report_name: stinson
    attack: stinson
 - instagram_attacks:
    report_name: toaster
    attack: toaster
 - instagram_attacks:
    report_name: valencia
    attack: valencia
 - instagram_attacks:
    report_name: walden
    attack: walden
 - instagram_attacks:
    report_name: willow
    attack: willow
 - instagram_attacks:
    report_name: xpro2
    attack: xpro2
