algorithms:
  arwgan:
    params:
      options_file_path: ./submodules/ARWGAN/pretrain/options-and-config.pickle
      checkpoint_file_path: ./submodules/ARWGAN/pretrain/checkpoints/ARWGAN.pyt
      module_path: ./submodules/ARWGAN

metrics:
  - PSNR
  - SSIM
  - LPIPS
  - BER

datasets:
  - DiffusionDB:
      path: /fast-drive/aakimenkov/img-watermarking-test/diffusionDB-filtered/

attacks:
  - Identity
  - JPEG: 
      report_name: jpeg_50
      quality: 50
  - JPEG:
      report_name: jpeg_20
      quality: 20


pipeline:
  result_path: ./test_results/arwgan
  aggregators:
    - CSV:
        table_name: table