algorithms:
  arwgan:
    params:
      options_file_path: ./model_files/arwgan/options-and-config.pickle
      checkpoint_file_path: ./model_files/arwgan/checkpoints/ARWGAN.pyt
      module_path: ./submodules/ARWGAN
      device: cuda

post_embed_metrics:
{% include 'common/post_embed_metrics.yml' %} 
post_attack_metrics:
{% include 'common/post_attack_metrics.yml' %} 
post_extract_metrics:
{% include 'common/post_extract_metrics.yml' %} 

datasets:
{% include 'common/diffusiondb.yml' %}

attacks:
{% include 'common/distortions.yml' %}

pipeline:
  result_path: ./test_results/arwgan
  aggregators:
    - CSV:
        table_name: table