algorithms:
  audioseal:
    params:
      device: cpu

post_embed_metrics:
  - SI_SNR
  - PESQ

post_extract_metrics:
  - ExtWm
  - BER
  - WER
  - TPR@xFPR:
      report_name: tpr@10e-2fpr
      fpr_rate: 0.01

datasets:
  - AudioFolderDataset:
      path: /home/do-op/Projects/docmarking/dm-audio/dataset/classic-v1/
      sample_rate: 16000

attacks:
  - Identity

pipeline:
  result_path: ./test_results/audioseal
  aggregators:
    - CSV:
        table_name: table