algorithms:
  cin:
    params:
      yaml_config_path: ./cin_weights/opt.yml
      checkpoint_path: ./cin_weights/cinNet&nsmNet.pth
      pre_noise_policy: pre_noise_nsm
      device: cuda
      module_path: ./submodules/CIN

metrics:
  - PSNR
  - SSIM
  - LPIPS
  - BER

datasets:
  - DiffusionDB:
      path: /fast-drive/aakimenkov/img-watermarking-test/diffusionDB-filtered/

attacks:
  - Identity
  - JPEG: 
      report_name: jpeg_50
      quality: 50
  - JPEG:
      report_name: jpeg_20
      quality: 20


pipeline:
  result_path: ./test_results/cin
  aggregators:
    - CSV:
        table_name: table