algorithms:
  cin:
    params:
      yaml_config_path: ./model_files/cin/opt.yml
      checkpoint_path: ./model_files/cin/cinNet&nsmNet.pth
      pre_noise_policy: pre_noise_nsm
      device: cuda
      module_path: ./submodules/CIN

metrics:
{% include 'metrics.yml' %} 

datasets:
  - DiffusionDB:
      path: datasets/diffusiondb

attacks:
{% include 'distortions.yml' %} 


pipeline:
  result_path: ./test_results/cin
  aggregators:
    - CSV:
        table_name: table