algorithms:
  dct_marker:
    params:
      width: 256
      height: 256
      wm_length: 100
      block_size: 256
      ampl1: 0.01
      ampl_ratio: 0.7
      lambda_h: 4

metrics:
  - PSNR
  - SSIM
  - LPIPS
  - BER

datasets:
  - DiffusionDB:
      path: /hdd/diffusiondb/filtered 

augmentations:
  - Identity
  # - jpeg: 
  #     quality: 50
  # - jpeg:
  #     quality: 20


pipeline:
