algorithms:
  dct_marker:
      width: 256
      height: 256
      wm_length: 100
      block_size: 256
      ampl1: 0.01
      ampl_ratio: 0.7
      lambda_h: 4

metrics:
  - psnr
  - ssim
  - lpips
  - ber

datasets:
  diffusiondb

augmentations:
  - jpeg: 
      quality: 50
  - jpeg:
      quality: 20
  - rotate
  - smth


pipeline:
