algorithms:
  dct_marker:
    params:
      width: 256
      height: 256
      wm_length: 100
      block_size: 256
      ampl1: 0.01
      ampl_ratio: 0.7
      lambda_h: 4

metrics:
{% include 'metrics.yml' %} 

datasets:
  - DiffusionDB:
      path: datasets/diffusiondb

attacks:
{% include 'distortions.yml' %} 
  - vaeattack
  - FluxRegeneration:
      sequential_cpu_offload: true
  - FluxRinsing:
      sequential_cpu_offload: true


pipeline:
  result_path: ./test_results/dct
  aggregators:
    - CSV:
        table_name: table