# Demo testing config. Recommended to run as (venv) wibench -config config/demo.yml -d
algorithms:
  trustmark: # Watermarking algorithm and its parameters
    params:
      wm_length: 100
      model_type: Q
      wm_strength: 0.75
      device: cuda

post_embed_metrics: # Watermark impeccability metrics
  - PSNR
  - SSIM
  - LPIPS
post_attack_metrics: # Visual quality of attacked image
  - PSNR
  - SSIM
  - LPIPS
post_extract_metrics: # Extraction effectiveness after attack
  - BER
  - TPR@xFPR:
      report_name: tpr@0.1%fpr
      fpr_rate: 0.001

datasets: # Dataset of images to test on
  - DiffusionDB:
      cache_dir: ./datasets/diffusiondb 
      subset: 2m_first_5k
      skip_nsfw: true
      samples_range: [0, 9] # Test on 10 images: 0, ..., 9

attacks:
  - Identity # No attack, just pass marked image
  - JPEG:
      report_name: jpeg_50
      quality: 50
  - gaussianblur:
      report_name: gaussianblur_5
      kernel_size: 5
  - gaussiannoise:
      report_name: noise_005
      sigma: 0.05
  - rotate:
      report_name: rotate_30
      angle: 30    

pipeline:
  seed: 42
  result_path: ./test_results/trustmark_demo # Path to save result, including all images (with -d flag)
  aggregators:
    - CSV: # Aggregate results in .csv file in result_path folder
        table_name: table
  min_batch_size: 1 # Minimal number of images to aggregate simultaneously
  workers: 2 # parallel execution
  cuda_visible_devices: 0, 1 # Run on machine with multiple GPU