algorithms:
  dft_circle:
    params:
      alpha: 600

metrics:
  - PSNR
  - SSIM
  - LPIPS
  - Result

datasets:
  - DiffusionDB:
      path: datasets/diffusiondb

attacks:
{% include 'distortions.yml' %}
  - vaeattack
  - FluxRegeneration:
      sequential_cpu_offload: true
  - FluxRinsing:
      sequential_cpu_offload: true


pipeline:
  result_path: ./test_results/dft_circle
  aggregators:
    - CSV:
        table_name: table