algorithms:
  dft_circle:
    params:
      alpha: 600

metrics:
  - PSNR
  - SSIM
  - LPIPS
  - Result

datasets:
{% include 'common/datasets.yml' %}

attacks:
{% include 'common/distortions.yml' %}


pipeline:
  result_path: ./test_results/dft_circle
  aggregators:
    - CSV:
        table_name: table