  - Identity
  - JPEG:
      report_name: jpeg_80
      quality: 80
  - JPEG:
      report_name: jpeg_50
      quality: 50
  - JPEG:
      report_name: jpeg_20
      quality: 20
  - rotate90:
      direction: counter
  - rotate:
      report_name: rotate_30
      angle: 30
  - rotate:
      report_name: rotate_60
      angle: 60
  - gaussianblur:
      report_name: gaussianblur_3
      kernel_size: 3
  - gaussianblur:
      report_name: gaussianblur_5
      kernel_size: 5
  - gaussianblur:
      report_name: gaussianblur_7
      kernel_size: 7
  - gaussiannoise:
      report_name: noise_003
      sigma: 0.03
  - gaussiannoise:
      report_name: noise_005
      sigma: 0.05
  - gaussiannoise:
      report_name: noise_008
      sigma: 0.08
  - centercrop:
      report_name: centercrop_30
      ratio: 0.3
  - centercrop:
      report_name: centercrop_50
      ratio: 0.5
  - centercrop:
      report_name: centercrop_80
      ratio: 0.8
  - resize:
      report_name: resize_0.5
      x_ratio: 0.5
      y_ratio: 0.5
  - resize:
      report_name: resize_2
      x_ratio: 2
      y_ratio: 2
  - resize:
      report_name: resize_x0.5
      x_ratio: 0.5
      y_ratio: 1
  - randomcropout:
      report_name: randomcropout_30
      ratio: 0.3
  - randomcropout:
      report_name: randomcropout_50
      ratio: 0.5
  - randomcropout:
      report_name: randomcropout_80
      ratio: 0.8
  - brightness:
      factor: 1.2
  - contrast:
      factor: 1.2