algorithms:
  dwt_svm:
    params:
      threshold: 56

metrics:
{% include 'metrics.yml' %} 

datasets:
  - DiffusionDB:
      path: datasets/diffusiondb

attacks:
{% include 'distortions.yml' %} 
  - vaeattack
  - FluxRegeneration:
      sequential_cpu_offload: true
  - FluxRinsing:
      sequential_cpu_offload: true


pipeline:
  result_path: ./test_results/dwt_svm
  aggregators:
    - CSV:
        table_name: table