algorithms:
  hidden:
    params:
      runs_root: ./submodules/HiDDeN/experiments
      run_name: combined-noise
      module_path: ./submodules/HiDDeN
      device: cuda

metrics:
{% include 'metrics.yml' %} 

datasets:
  - DiffusionDB:
      path: datasets/diffusiondb

attacks:
{% include 'distortions.yml' %} 


pipeline:
  result_path: ./test_results/hidden
  aggregators:
    - CSV:
        table_name: table