algorithms:
  hidden:
    params:
      runs_root: ./submodules/HiDDeN/experiments
      run_name: combined-noise
      module_path: ./submodules/HiDDeN
metrics:
  - PSNR
  - SSIM
  - LPIPS
  - BER

datasets:
  - DiffusionDB:
      path: /fast-drive/aakimenkov/img-watermarking-test/diffusionDB-filtered/

attacks:
  - Identity
  - JPEG: 
      report_name: jpeg_50
      quality: 50
  - JPEG:
      report_name: jpeg_20
      quality: 20


pipeline:
  result_path: ./test_results/hidden
  aggregators:
    - CSV:
        table_name: table