algorithms:
  - dwt_dct
  - dwt_dct_svd
  - riva_gan

metrics:
  - PSNR
  - SSIM
  - LPIPS
  - BER

datasets:
  - DiffusionDB:
      path: datasets/diffusiondb

attacks:
{% include 'distortions.yml' %}
  - vaeattack
  - FluxRegeneration:
      sequential_cpu_offload: true
  - FluxRinsing:
      sequential_cpu_offload: true


pipeline:
  result_path: ./test_results/invisible_watermark
  aggregators:
    - CSV:
        table_name: table
