algorithms:
  - riva_gan

post_embed_metrics:
{% include 'common/post_embed_metrics.yml' %} 
post_attack_metrics:
{% include 'common/post_attack_metrics.yml' %} 
post_extract_metrics:
{% include 'common/post_extract_metrics.yml' %} 

datasets:
{% include 'common/datasets_lim.yml' %}

attacks:
{% include 'common/resourceintensive_attacks.yml' %}

pipeline:
  result_path: /test/test_results/invisible_watermark_msu
  aggregators:
    - CSV:
        table_name: table