algorithms:
  - dwt_dct
  - dwt_dct_svd
  - riva_gan

metrics:
{% include 'common/metrics.yml' %} 

datasets:
{% include 'common/diffusiondb.yml' %}

attacks:
{% include 'common/distortions.yml' %}


pipeline:
  result_path: ./test_results/invisible_watermark
  aggregators:
    - CSV:
        table_name: table
