algorithms:
  - riva_gan

metrics:
{% include 'common/metrics.yml' %} 

datasets:
{% include 'common/datasets.yml' %}

attacks:
{% include 'common/resourceintensive_attacks.yml' %}

pipeline:
  result_path: ./test_results/invisible_watermark_msu
  aggregators:
    - CSV:
        table_name: table