algorithms:
  - dwt_dct
  - dwt_dct_svd
  - riva_gan

metrics:
  - PSNR
  - SSIM
  - LPIPS
  - BER

datasets:
  - DiffusionDB:
      path: /hdd/diffusiondb/filtered 

attacks:
  - Identity
  - JPEG: 
      report_name: jpeg_50
      quality: 50
  - JPEG:
      report_name: jpeg_20
      quality: 20


pipeline:
  result_path: ./test_results/invisible_watermark
  aggregators:
    - CSV:
        table_name: table