algorithms:
  NormSpace:
    params:
      sample_rate: 16000
      watermark_length: 40
      delta: 0.03
      wavelet: db1

post_embed_metrics:
  - SI_SNR
  # - PESQ
  # - STOI
  # - NISQA
  # - DNSMOS
  # - SECS

post_extract_metrics:
  - ExtWm
  - BER
  - WER

datasets:
  - LibriSpeech:
      cache_dir: /fast-drive/redkin.d/hf_cache/librispeech
      subset: clean
      split: test
      sample_range: [0, 2]

attacks:
{% include 'common/band_filters.yml' %}

pipeline:
  result_path: ./test_results/norm_space
  aggregators:
    - CSV:
        table_name: table_bands_search
