algorithms:
  ssl_watermarking:
    params:
      method: multibit
      backbone_weights_path: ./dino_r50_plus.pth
      normlayer_weights_path: ./out2048_yfcc_orig.pth
      module_path: ./submodules/ssl_watermarking
      epochs: 100
      optimizer_alg: Adam
      optimizer_lr: 0.01
      lambda_w: 20.
      lambda_i: 1.
      target_psnr: 42.
      target_fpr: 1e-6
      num_bits: 32
      device: cuda

metrics:
  - PSNR
  - SSIM
  - LPIPS
  - BER

datasets:
  - DiffusionDB:
      path: /fast-drive/aakimenkov/img-watermarking-test/diffusionDB-filtered/

attacks:
  - Identity
  - JPEG: 
      report_name: jpeg_50
      quality: 50
  - JPEG:
      report_name: jpeg_20
      quality: 20


pipeline:
  result_path: ./test_results/ssl_watermarking_multibit
  aggregators:
    - CSV:
        table_name: table