# Demo testing config; it is recommended to run as: (venv) python -m wibench -config config/trustmark_demo.yml -d
algorithms:
  trustmark:            # Watermarking algorithm and its parameters
    params:
      wm_length: 100
      model_type: Q
      wm_strength: 0.75
      device: cpu

post_embed_metrics:         # Watermark impeccability metrics
  - PSNR
  - SSIM

post_attack_metrics:        # Visual quality of attacked image
  - PSNR
  - SSIM

post_extract_metrics:       # Extraction effectiveness after attack
  - TPR@xFPR:
      report_name: tpr@0.1%fpr
      fpr_rate: 0.001

datasets:                   # Dataset of images to test on
  - DiffusionDB:
      cache_dir: ./datasets/diffusiondb 
      subset: 2m_first_5k
      skip_nsfw: true
      samples_range: [0, 9]   # Test with 10 images: 0, ..., 9

attacks:                    # Attacks on watermarks
{% include 'common/distortions.yml' %}

pipeline:
  result_path: ./test_results/trustmark   # Path to save results, including all images (with -d flag)
  aggregators:
    - CSV:                  # Aggregate results in .csv file in result_path folder
        table_name: table