algorithms:
  trustmark:
    params:
      wm_length: 100
      model_type: Q
      wm_strength: 0.75
      device: cpu

metrics:
{% include 'common/metrics.yml' %} 

datasets:
{% include 'common/datasets.yml' %}

attacks:
{% include 'common/distortions.yml' %}


pipeline:
  result_path: ./test_results/trustmark
  aggregators:
    - CSV:
        table_name: table