algorithms:
  - trustmark

post_extract_metrics:
  - ExtWm
  - BER
  - EmpiricalTPR@xFPR:
      report_name: etpr@10e-1fpr
      fpr_rate: 0.1
      algorithm: trustmark
      dataset: mscoco
      dataset_params:
        split: train
        sample_range: [0, 99]
      random_extracts_path: "./random_extracts_0.1.csv"
  - EmpiricalTPR@xFPR:
      report_name: etpr@10e-2fpr
      fpr_rate: 0.01
      algorithm: trustmark
      dataset: mscoco
      dataset_params:
        split: train
        sample_range: [0, 999]
      random_extracts_path: "./random_extracts_0.01.csv"
  - EmpiricalTPR@xFPR:
      report_name: etpr@10e-3fpr
      fpr_rate: 0.001
      algorithm: trustmark
      dataset: mscoco
      dataset_params:
        split: train
        sample_range: [0, 9999]
      random_extracts_path: "./random_extracts_0.001.csv"
  - TPR@xFPR:
      report_name: tpr@10e-1fpr
      fpr_rate: 0.1
  - TPR@xFPR:
      report_name: tpr@10e-2fpr
      fpr_rate: 0.01
  - TPR@xFPR:
      report_name: tpr@10e-3fpr
      fpr_rate: 0.001
  - TPR@xFPR:
      report_name: tpr@10e-4fpr
      fpr_rate: 0.0001
  - TPR@xFPR:
      report_name: tpr@10e-5fpr
      fpr_rate: 0.00001
  - TPR@xFPR:
      report_name: tpr@10e-6fpr
      fpr_rate: 0.000001
  - TPR@xFPR:
      report_name: tpr@10e-7fpr
      fpr_rate: 0.0000001
  - TPR@xFPR:
      report_name: tpr@10e-8fpr
      fpr_rate: 0.00000001

datasets:
{% include 'common/mscoco.yml' %}

attacks:
 - Identity
 - JPEG:
    report_name: jpeg_20
    quality: 20
 - JPEG:
    report_name: jpeg_20
    quality: 20
 - JPEG:
    report_name: jpeg_30
    quality: 30
 - JPEG:
    report_name: jpeg_40
    quality: 40
 - JPEG:
    report_name: jpeg_50
    quality: 50
 - JPEG:
    report_name: jpeg_60
    quality: 60
 - JPEG:
    report_name: jpeg_70
    quality: 70
 - JPEG:
    report_name: jpeg_80
    quality: 80
 - JPEG:
    report_name: jpeg_90
    quality: 90


pipeline:
  result_path: ./test_results/trustmark_empirical_tpr@fpr
  min_batch_size: 1
  aggregators:
    - CSV:
        table_name: table