algorithms:
  trustmark:
    params:
      wm_length: 100
      model_type: Q
      wm_strength: 0.75
      device: cuda # {cpu, cuda}

metrics:
{% include 'common/metrics.yml' %} 

datasets:
{% include 'common/datasets.yml' %}

attacks:
{% include 'common/resourceintensive_attacks.yml' %}

pipeline:
  result_path: ./test_results/trustmark_msu
  aggregators:
    - CSV:
        table_name: table