algorithms:
  watermark_anything:
    scaling_w: 1.5
    wm_length: 32
    module_path: ./submodules/watermark_anything
    ckpt_path: ./model_files/watermark_anything/wam_mit.pth
    params_path: src/imgmarkbench/algorithms/watermark_anything/configs/params.json
    device: cuda

post_embed_metrics:
{% include 'common/post_embed_metrics.yml' %} 
post_attack_metrics:
{% include 'common/post_attack_metrics.yml' %} 
post_extract_metrics:
{% include 'common/post_extract_metrics.yml' %} 

datasets:
{% include 'common/datasets_lim.yml' %}

attacks:
{% include 'common/resourceintensive_attacks.yml' %}

pipeline:
  result_path: /test/test_results/watermark_anything_msu
  aggregators:
    - CSV:
        table_name: table
