algorithms:
  watermark_anything:
    scaling_w: 1.5
    wm_length: 32
    module_path: ./submodules/watermark_anything
    ckpt_path: ./model_files/watermark_anything/wam_mit.pth
    params_path: src/imgmarkbench/algorithms/watermark_anything/configs/params.json
    device: cuda


metrics:
{% include 'common/metrics.yml' %} 

datasets:
{% include 'common/datasets.yml' %}

attacks:
{% include 'common/resourceintensive_attacks.yml' %}


pipeline:
  result_path: ./test_results/watermark_anything_msu
  aggregators:
    - CSV:
        table_name: table