  - Filter:
      report_name: lowpass_1
      filter_type: lowpass
      freq_1: 1
  - Filter:
      report_name: lowpass_500
      filter_type: lowpass
      freq_1: 500
  - Filter:
      report_name: lowpass_1000
      filter_type: lowpass
      freq_1: 1000
  - Filter:
      report_name: lowpass_1250
      filter_type: lowpass
      freq_1: 1250
  - Filter:
      report_name: lowpass_1500
      filter_type: lowpass
      freq_1: 1500
  - Filter:
      report_name: lowpass_1750
      filter_type: lowpass
      freq_1: 1750
  - Filter:
      report_name: lowpass_2000
      filter_type: lowpass
      freq_1: 2000
  - Filter:
      report_name: lowpass_2250
      filter_type: lowpass
      freq_1: 2250
  - Filter:
      report_name: lowpass_2500
      filter_type: lowpass
      freq_1: 2500
  - Filter:
      report_name: lowpass_2750
      filter_type: lowpass
      freq_1: 2750
  - Filter:
      report_name: lowpass_3000
      filter_type: lowpass
      freq_1: 3000
  - Filter:
      report_name: lowpass_3250
      filter_type: lowpass
      freq_1: 3250
  - Filter:
      report_name: lowpass_3500
      filter_type: lowpass
      freq_1: 3500
  - Filter:
      report_name: lowpass_4000
      filter_type: lowpass
      freq_1: 4000
  - Filter:
      report_name: lowpass_4500
      filter_type: lowpass
      freq_1: 4500
  - Filter:
      report_name: lowpass_5000
      filter_type: lowpass
      freq_1: 5000
  - Filter:
      report_name: lowpass_6000
      filter_type: lowpass
      freq_1: 6000
  - Filter:
      report_name: lowpass_7000
      filter_type: lowpass
      freq_1: 7000
  - Filter:
      report_name: lowpass_7900
      filter_type: lowpass
      freq_1: 7900
  - Filter:
      report_name: highpass_1
      filter_type: highpass
      freq_1: 1
  - Filter:
      report_name: highpass_1000
      filter_type: highpass
      freq_1: 1000
  - Filter:
      report_name: highpass_2000
      filter_type: highpass
      freq_1: 2000
  - Filter:
      report_name: highpass_2250
      filter_type: highpass
      freq_1: 2250
  - Filter:
      report_name: highpass_2500
      filter_type: highpass
      freq_1: 2500
  - Filter:
      report_name: highpass_2750
      filter_type: highpass
      freq_1: 2750
  - Filter:
      report_name: highpass_3000
      filter_type: highpass
      freq_1: 3000
  - Filter:
      report_name: highpass_3250
      filter_type: highpass
      freq_1: 3250
  - Filter:
      report_name: highpass_3500
      filter_type: highpass
      freq_1: 3500
  - Filter:
      report_name: highpass_3750
      filter_type: highpass
      freq_1: 3750
  - Filter:
      report_name: highpass_4000
      filter_type: highpass
      freq_1: 4000
  - Filter:
      report_name: highpass_4250
      filter_type: highpass
      freq_1: 4250
  - Filter:
      report_name: highpass_4500
      filter_type: highpass
      freq_1: 4500
  - Filter:
      report_name: highpass_5000
      filter_type: highpass
      freq_1: 5000
  - Filter:
      report_name: highpass_6000
      filter_type: highpass
      freq_1: 6000
  - Filter:
      report_name: highpass_7000
      filter_type: highpass
      freq_1: 7000
  - Filter:
      report_name: highpass_7900
      filter_type: highpass
      freq_1: 7900
