  - &dataset_name CommonVoice: &dataset_params
      languages:
        - en
        - de
        - fr
        - es
        - it
        - ru
        - uk
        - pl
        - ar
        - hi
        - ja
        - zh-CN
      split: test
      sample_range: [0, 2500]
