  - Identity
  - Cut:
      report_name: cut_start_10ms
      duration_ms: 10
      mode: start
  - Cut:
      report_name: cut_start_100ms
      duration_ms: 100
      mode: start
  - Cut:
      report_name: cut_start_500ms
      duration_ms: 500
      mode: start
  - Cut:
      report_name: cut_start_1s
      duration_ms: 1000
      mode: start
  - Cut:
      report_name: cut_end_100ms
      duration_ms: 100
      mode: end
  - Cut:
      report_name: cut_random_100ms
      duration_ms: 100
      mode: random
  - TimeStretch:
      report_name: time_stretch_101%
      rate: 1.01
  - TimeStretch:
      report_name: time_stretch_105%
      rate: 1.05
  - TimeStretch:
      report_name: time_stretch_110%
      rate: 1.1
  - TimeStretch:
      report_name: time_stretch_140%
      rate: 1.4
  - InvertedTimeStretch:
      report_name: inv_time_stretch_80%
      rate: 0.8
  - Pitch:
      report_name: pitch_shift_1
      cents: 1
  - Pitch:
      report_name: pitch_shift_5
      cents: 5
  - FlipSamples:
      num_flips: 100
      duration: 0.5
  - ZeroCrossInserts:
      pause_length: 20
      min_distance: 1.0
  - ReplacementAttack:
      block_size: 1024
      overlap_factor: 0.75
      lower_bound: 0
      upper_bound: 10
      k: 100
      use_masking: False
      search_window_sec: 0.0
      search_dims: 0
      tile_size: 256