  - Identity
  - Cut:
      duration_ms: 10
      mode: start
  - Cut:
      duration_ms: 100
      mode: start
  - Cut:
      duration_ms: 500
      mode: start
  - Cut:
      duration_ms: 1000
      mode: start
  - Cut:
      duration_ms: 100
      mode: end
  - Cut:
      duration_ms: 100
      mode: random
  - TimeStretch:
      rate: 1.01
  - TimeStretch:
      rate: 1.05
  - TimeStretch:
      rate: 1.1
  - TimeStretch:
      rate: 1.4
  - InvertedTimeStretch:
      rate: 0.8
  - PitchShift:
      cents: 1
  - PitchShift:
      cents: 5
  - FlipSamples:
      num_flips: 100
      duration: 0.5
  - ZeroCrossInserts:
      pause_length: 20
      min_distance: 1.0
  - ReplacementAttack:
      block_size: 1024
      overlap_factor: 0.75
      lower_bound: 0
      upper_bound: 10
      k: 100
      use_masking: False
      search_window_sec: 0.0
      search_dims: 0
      tile_size: 256