  - EmpiricalTPR@xFPR:
      report_name: etpr@10e-1fpr
      fpr_rate: 0.1
      algorithm: *alg_name
      algorithm_params:
        <<: *alg_params
      dataset: *dataset_name
      dataset_params:
        <<: *dataset_params
        sample_range: [0, 99]
      random_extracts_path: "./random_extracts_0.1.csv"
{% if alg_name in ["perth"] %}
      method_type: zero-bit
{% else %}
      method_type: multi-bit
{% endif %}
  - EmpiricalTPR@xFPR:
      report_name: etpr@10e-2fpr
      fpr_rate: 0.01
      algorithm: *alg_name
      algorithm_params:
        <<: *alg_params
      dataset: *dataset_name
      dataset_params:
        <<: *dataset_params
        sample_range: [0, 999]
      random_extracts_path: "./random_extracts_0.01.csv"
{% if alg_name in ["perth"] %}
      method_type: zero-bit
{% else %}
      method_type: multi-bit
{% endif %}
  - EmpiricalTPR@xFPR:
      report_name: etpr@10e-3fpr
      fpr_rate: 0.001
      algorithm: *alg_name
      algorithm_params:
        <<: *alg_params
      dataset: *dataset_name
      dataset_params:
        <<: *dataset_params
        sample_range: [0, 9999]
      random_extracts_path: "./random_extracts_0.001.csv"
{% if alg_name in ["perth"] %}
      method_type: zero-bit
{% else %}
      method_type: multi-bit
{% endif %}
