  - &dataset_name LibriSpeech: &dataset_params
      report_name: ls_{{ ls_split | default("test.clean") }}
      subset: all
      split: {{ ls_split | default("test.clean") }}
      sample_range: [0, 2500]
