algorithms:
  cryptomark:
    params:
      profile: light
      target_rate: 16000

datasets:
{% include 'common/speech_10k.yml' %}

post_embed_metrics:
{% include 'common/post_embed_metrics.yml' %}

post_extract_metrics:
{% include 'common/post_extract_metrics.yml' %}
{% include 'common/tpr@10e-6fpr.yml' %}

attacks:
  - Identity
{% include 'common/signal.yml' %}
{% include 'common/effects.yml' %}
{% include 'common/enhancements.yml' %}
{% include 'common/desynchronization.yml' %}
{% include 'common/compression.yml' %}
{% include 'common/malicious.yml' %}

pipeline:
  result_path: ./test_results/cryptomark
  aggregators:
    - CSV:
        table_name: table
