{% set ls_split = "test.clean" %}

algorithms:
  &alg_name cryptomark: &alg_params
    params:
      profile: light
      target_rate: 16000

datasets:
{% include 'common/librispeech.yml' %}

post_embed_metrics:
{% include 'common/post_embed_metrics.yml' %}

post_extract_metrics:
{% include 'common/post_extract_metrics.yml' %}

attacks:
{% include 'common/distortions.yml' %}

pipeline:
  result_path: ./test_results/cryptomark
  aggregators:
    - CSV:
        table_name: table
