algorithms:
  DCT-B1:
    params:
      sample_rate: 16000
      watermark_length: 24
      lt: 23
      lw: 1486
      band_size: 30
      lG1: 24
      seed: 12345

post_embed_metrics:
{% include 'common/post_embed_metrics.yml' %}

post_extract_metrics:
{% include 'common/post_extract_metrics.yml' %}

datasets:
{% include 'common/librispeech.yml' %}

attacks:
{% include 'common/distortions.yml' %}

pipeline:
  result_path: ./test_results/dct_b1
  aggregators:
    - CSV:
        table_name: table
