{% set ls_split = "test.clean" %}

algorithms:
  &alg_name DCT-B1: &alg_params
    params:
      sample_rate: 16000
      watermark_length: 24
      lt: 23
      lw: 1486
      band_size: 30
      lG1: 24
      seed: 12345

datasets:
{% include 'common/librispeech.yml' %}

post_embed_metrics:
{% include 'common/post_embed_metrics.yml' %}

post_extract_metrics:
{% include 'common/post_extract_metrics.yml' %}

attacks:
{% include 'common/distortions.yml' %}

pipeline:
  result_path: ./test_results/dct_b1
  aggregators:
    - CSV:
        table_name: table
