{% set ls_split = "test.clean" %}

algorithms:
  &alg_name dnn_audio: &alg_params
    params:
      device: cuda

datasets:
{% include 'common/librispeech.yml' %}

post_embed_metrics:
{% include 'common/post_embed_metrics.yml' %}

post_extract_metrics:
{% include 'common/post_extract_metrics.yml' %}

attacks:
{% include 'common/distortions.yml' %}

pipeline:
  result_path: ./test_results/dnn_audio
  aggregators:
    - CSV:
        table_name: table