algorithms:
  EchoHidingPositive:
    params:
      sample_rate: 16000
      watermark_length: 16
      frame_length: 512
      overlap: 0.5
      control_strength: 0.2
      num_reps: 3
      seed: 12345
      delay11: 100
      delay10: 110
      delay01: 120
      delay00: 130

post_embed_metrics:
{% include 'common/post_embed_metrics.yml' %}

post_extract_metrics:
{% include 'common/post_extract_metrics.yml' %}

datasets:
{% include 'common/librispeech.yml' %}

attacks:
{% include 'common/distortions.yml' %}


pipeline:
  result_path: ./test_results/echo_positive
  aggregators:
    - CSV:
        table_name: table
