algorithms:
  Patchwork:
    params:
      sample_rate: 16000
      watermark_length: 40
      fs: 3000
      fe: 7000
      k1: 0.195
      k2: 0.08

post_embed_metrics:
{% include 'common/post_embed_metrics.yml' %}

post_extract_metrics:
{% include 'common/post_extract_metrics.yml' %}

datasets:
{% include 'common/librispeech.yml' %}

attacks:
{% include 'common/distortions.yml' %}

pipeline:
  result_path: ./test_results/patchwork
  aggregators:
    - CSV:
        table_name: table
