algorithms:
  &alg_name perth: &alg_params
    params:
      device: cuda

datasets:
{% include 'common/audioset.yml' %}

post_embed_metrics:
  - SI_SNR
  - PESQ
  - STOI
  - NISQA
  - DNSMOS
  - SECS

post_extract_metrics:
  - Result
{% include 'common/empirical_zerobit_tpr@fpr.yml' %}

attacks:
  - Identity
{% include 'common/signal.yml' %}
{% include 'common/effects.yml' %}
{% include 'common/enhancements.yml' %}
{% include 'common/desynchronization.yml' %}
{% include 'common/compression.yml' %}
{% include 'common/malicious.yml' %}

pipeline:
  result_path: ./test_results/perth
  aggregators:
    - CSV:
        table_name: table