{% set ls_split = "test.clean" %}

algorithms:
  &alg_name perth: &alg_params
    params:
      device: cpu

datasets:
{% include 'common/librispeech.yml' %}

post_embed_metrics:
{% include 'common/post_embed_metrics.yml' %}

post_extract_metrics:
{% include 'common/post_extract_metrics.yml' %}

attacks:
{% include 'common/distortions.yml' %}

pipeline:
  result_path: ./test_results/perth
  aggregators:
    - CSV:
        table_name: table