algorithms:
  QIM:
    params:
      sample_rate: 16000
      watermark_length: 40
      delta: 0.01
      repetitions: 64
      seed: 12345

post_embed_metrics:
{% include 'common/post_embed_metrics.yml' %}

post_extract_metrics:
{% include 'common/post_extract_metrics.yml' %}

datasets:
{% include 'common/librispeech.yml' %}

attacks:
{% include 'common/distortions.yml' %}

pipeline:
  result_path: ./test_results/qim
  aggregators:
    - CSV:
        table_name: table
