algorithms:
  SpreadSpectrum:
    params:
      sample_rate: 16000
      watermark_length: 10
      frame_length: 512
      overlap: 0.0
      control_strength: 0.1
      num_reps: 3
      seed: 12345

post_embed_metrics:
{% include 'common/post_embed_metrics.yml' %}

post_extract_metrics:
{% include 'common/post_extract_metrics.yml' %}

datasets:
{% include 'common/librispeech.yml' %}

attacks:
{% include 'common/distortions.yml' %}

pipeline:
  result_path: ./test_results/spread_spectrum
  aggregators:
    - CSV:
        table_name: table
