algorithms:
  wavmark:
    params:
      device: cpu

post_embed_metrics:
{% include 'common/post_embed_metrics.yml' %}

post_extract_metrics:
{% include 'common/post_extract_metrics.yml' %}

datasets:
{% include 'common/librispeech.yml' %}

attacks:
{% include 'common/distortions.yml' %}

pipeline:
  result_path: ./test_results/wavmark
  aggregators:
    - CSV:
        table_name: table